CREATE TABLE IF NOT EXISTS users(
	uid VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(email),
    UNIQUE(email)
);