CREATE TABLE IF NOT EXISTS authTokens(
	uid VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL,
    ownerId VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    PRIMARY KEY(uid),
    UNIQUE(uid)
);